export const path = {
    public: '',
    home: '/',
    login: 'login',
    register: 'register',
    courses: 'courses/:categoryId',
    course: 'course/:courseId',
    info: 'my-info/:userId',
    profile: 'user/:userId',
    teach: 'teach',
    myCourse: 'my-course',
    allReview: 'all-reviews',
    about: 'about',
    search: 'search/:keyword',
    admin: 'admin',
    manageCourse: 'manage-course',
    manageUser: 'manage-user',
    manageCategory: 'manage-category',
};